# Real universities for the learner dropdown (searchable). Keep Community last.
UNIVERSITIES = [
    ("Bugema University", "Uganda", "university"),
    ("Makerere University", "Uganda", "university"),
    ("Kyambogo University", "Uganda", "university"),
    ("Mbarara University of Science and Technology", "Uganda", "university"),
    ("Uganda Christian University", "Uganda", "university"),
    ("Kampala International University", "Uganda", "university"),
    ("Uganda Martyrs University", "Uganda", "university"),
    ("Ndejje University", "Uganda", "university"),
    ("Nkumba University", "Uganda", "university"),
    ("Busitema University", "Uganda", "university"),
    ("Gulu University", "Uganda", "university"),
    ("Lira University", "Uganda", "university"),
    ("Soroti University", "Uganda", "university"),
    ("Kabale University", "Uganda", "university"),
    ("Muni University", "Uganda", "university"),
    ("Mountains of the Moon University", "Uganda", "university"),
    ("Islamic University in Uganda", "Uganda", "university"),
    ("Victoria University Kampala", "Uganda", "university"),
    ("Cavendish University Uganda", "Uganda", "university"),
    ("International University of East Africa", "Uganda", "university"),
    ("St. Augustine International University", "Uganda", "university"),
    ("Livingstone International University", "Uganda", "university"),
    ("Africa Renewal University", "Uganda", "university"),
    ("Bishop Stuart University", "Uganda", "university"),
    ("Uganda Pentecostal University", "Uganda", "university"),
    ("Kumi University", "Uganda", "university"),
    ("All Saints University Lango", "Uganda", "university"),
    ("Ankole Western University", "Uganda", "university"),
    ("Team University Uganda", "Uganda", "university"),
    ("Stafford University Uganda", "Uganda", "university"),
    ("Université de Kinshasa (UNIKIN)", "DRC", "university"),
    ("Université Officielle de Bukavu", "DRC", "university"),
    ("Université de Lubumbashi", "DRC", "university"),
    ("Université de Kisangani", "DRC", "university"),
    ("Université Pédagogique Nationale", "DRC", "university"),
    ("Université Catholique du Congo", "DRC", "university"),
    ("Université Protestante au Congo", "DRC", "university"),
    ("Université Kongo", "DRC", "university"),
    ("Université de Goma", "DRC", "university"),
    ("Université Officielle de Mbujimayi", "DRC", "university"),
    ("Université de Bandundu", "DRC", "university"),
    ("Université de Kikwit", "DRC", "university"),
    ("Université de Kindu", "DRC", "university"),
    ("Université Simon Kimbangu", "DRC", "university"),
    ("Université William Booth", "DRC", "university"),
    ("Université Cardinal Malula", "DRC", "university"),
    ("Université de l’Uélé", "DRC", "university"),
    ("Université de Bunia", "DRC", "university"),
    ("Université Notre Dame du Kasayi", "DRC", "university"),
    ("Université Catholique de Bukavu", "DRC", "university"),
    ("University of Nairobi", "Kenya", "university"),
    ("Kenyatta University", "Kenya", "university"),
    ("Strathmore University", "Kenya", "university"),
    ("Jomo Kenyatta University of Agriculture and Technology", "Kenya", "university"),
    ("Moi University", "Kenya", "university"),
    ("Egerton University", "Kenya", "university"),
    ("Maseno University", "Kenya", "university"),
    ("Technical University of Kenya", "Kenya", "university"),
    ("United States International University Africa", "Kenya", "university"),
    ("Mount Kenya University", "Kenya", "university"),
    ("Daystar University", "Kenya", "university"),
    ("Catholic University of Eastern Africa", "Kenya", "university"),
    ("University of Eldoret", "Kenya", "university"),
    ("Masinde Muliro University of Science and Technology", "Kenya", "university"),
    ("Dedan Kimathi University of Technology", "Kenya", "university"),
    ("Multimedia University of Kenya", "Kenya", "university"),
    ("University of Rwanda", "Rwanda", "university"),
    ("University of Kigali", "Rwanda", "university"),
    ("African Leadership University Rwanda", "Rwanda", "university"),
    ("University of Gitwe", "Rwanda", "university"),
    ("Adventist University of Central Africa", "Rwanda", "university"),
    ("University of Dar es Salaam", "Tanzania", "university"),
    ("Sokoine University of Agriculture", "Tanzania", "university"),
    ("Ardhi University", "Tanzania", "university"),
    ("Muhimbili University of Health and Allied Sciences", "Tanzania", "university"),
    ("University of Dodoma", "Tanzania", "university"),
    ("Nelson Mandela African Institution of Science and Technology", "Tanzania", "university"),
    ("Mzumbe University", "Tanzania", "university"),
    ("Open University of Tanzania", "Tanzania", "university"),
    ("Addis Ababa University", "Ethiopia", "university"),
    ("Bahir Dar University", "Ethiopia", "university"),
    ("Jimma University", "Ethiopia", "university"),
    ("Mekelle University", "Ethiopia", "university"),
    ("Hawassa University", "Ethiopia", "university"),
    ("University of Gondar", "Ethiopia", "university"),
    ("University of Khartoum", "Sudan", "university"),
    ("Sudan University of Science and Technology", "Sudan", "university"),
    ("University of Juba", "South Sudan", "university"),
    ("University of Somalia", "Somalia", "university"),
    ("Mogadishu University", "Somalia", "university"),
    ("University of Djibouti", "Djibouti", "university"),
    ("University of Burundi", "Burundi", "university"),
    ("Université Espoir d’Afrique", "Burundi", "university"),
    ("University of Zambia", "Zambia", "university"),
    ("Copperbelt University", "Zambia", "university"),
    ("Mulungushi University", "Zambia", "university"),
    ("University of Zimbabwe", "Zimbabwe", "university"),
    ("National University of Science and Technology Zimbabwe", "Zimbabwe", "university"),
    ("Midlands State University", "Zimbabwe", "university"),
    ("University of Malawi", "Malawi", "university"),
    ("Mzuzu University", "Malawi", "university"),
    ("Lilongwe University of Agriculture and Natural Resources", "Malawi", "university"),
    ("University of Botswana", "Botswana", "university"),
    ("Botswana International University of Science and Technology", "Botswana", "university"),
    ("University of Namibia", "Namibia", "university"),
    ("Namibia University of Science and Technology", "Namibia", "university"),
    ("University of Cape Town", "South Africa", "university"),
    ("University of the Witwatersrand", "South Africa", "university"),
    ("Stellenbosch University", "South Africa", "university"),
    ("University of Pretoria", "South Africa", "university"),
    ("University of Johannesburg", "South Africa", "university"),
    ("University of KwaZulu-Natal", "South Africa", "university"),
    ("Rhodes University", "South Africa", "university"),
    ("University of the Western Cape", "South Africa", "university"),
    ("Cape Peninsula University of Technology", "South Africa", "university"),
    ("Tshwane University of Technology", "South Africa", "university"),
    ("Durban University of Technology", "South Africa", "university"),
    ("North-West University", "South Africa", "university"),
    ("University of the Free State", "South Africa", "university"),
    ("Nelson Mandela University", "South Africa", "university"),
    ("University of South Africa", "South Africa", "university"),
    ("University of Limpopo", "South Africa", "university"),
    ("University of Venda", "South Africa", "university"),
    ("University of Fort Hare", "South Africa", "university"),
    ("Eduardo Mondlane University", "Mozambique", "university"),
    ("Universidade Pedagógica", "Mozambique", "university"),
    ("University of Mauritius", "Mauritius", "university"),
    ("University of Technology Mauritius", "Mauritius", "university"),
    ("University of Seychelles", "Seychelles", "university"),
    ("University of Antananarivo", "Madagascar", "university"),
    ("University of Ghana", "Ghana", "university"),
    ("Kwame Nkrumah University of Science and Technology", "Ghana", "university"),
    ("University of Cape Coast", "Ghana", "university"),
    ("Ashesi University", "Ghana", "university"),
    ("University of Education Winneba", "Ghana", "university"),
    ("Ghana Institute of Management and Public Administration", "Ghana", "university"),
    ("University of Lagos", "Nigeria", "university"),
    ("University of Ibadan", "Nigeria", "university"),
    ("Obafemi Awolowo University", "Nigeria", "university"),
    ("Ahmadu Bello University", "Nigeria", "university"),
    ("University of Nigeria Nsukka", "Nigeria", "university"),
    ("Covenant University", "Nigeria", "university"),
    ("University of Benin", "Nigeria", "university"),
    ("Federal University of Technology Akure", "Nigeria", "university"),
    ("Lagos State University", "Nigeria", "university"),
    ("University of Ilorin", "Nigeria", "university"),
    ("University of Port Harcourt", "Nigeria", "university"),
    ("Bayero University Kano", "Nigeria", "university"),
    ("American University of Nigeria", "Nigeria", "university"),
    ("Pan-Atlantic University", "Nigeria", "university"),
    ("University of Abuja", "Nigeria", "university"),
    ("Nnamdi Azikiwe University", "Nigeria", "university"),
    ("Federal University of Technology Minna", "Nigeria", "university"),
    ("University of Calabar", "Nigeria", "university"),
    ("Cheikh Anta Diop University", "Senegal", "university"),
    ("University of Thiès", "Senegal", "university"),
    ("Université Gaston Berger", "Senegal", "university"),
    ("University of Bamako", "Mali", "university"),
    ("University of Ouagadougou", "Burkina Faso", "university"),
    ("University of Abidjan", "Côte d’Ivoire", "university"),
    ("Institut National Polytechnique Félix Houphouët-Boigny", "Côte d’Ivoire", "university"),
    ("University of Lomé", "Togo", "university"),
    ("University of Abomey-Calavi", "Benin", "university"),
    ("University of Liberia", "Liberia", "university"),
    ("Fourah Bay College University of Sierra Leone", "Sierra Leone", "university"),
    ("University of The Gambia", "Gambia", "university"),
    ("University of Conakry", "Guinea", "university"),
    ("University of Nouakchott", "Mauritania", "university"),
    ("University of Niamey", "Niger", "university"),
    ("University of N’Djamena", "Chad", "university"),
    ("University of Yaoundé I", "Cameroon", "university"),
    ("University of Yaoundé II", "Cameroon", "university"),
    ("University of Buea", "Cameroon", "university"),
    ("University of Douala", "Cameroon", "university"),
    ("University of Ngaoundéré", "Cameroon", "university"),
    ("University of Dschang", "Cameroon", "university"),
    ("Omar Bongo University", "Gabon", "university"),
    ("Marien Ngouabi University", "Republic of the Congo", "university"),
    ("University of Bangui", "Central African Republic", "university"),
    ("University of São Tomé", "São Tomé and Príncipe", "university"),
    ("University of Equatorial Guinea", "Equatorial Guinea", "university"),
    ("Cairo University", "Egypt", "university"),
    ("Ain Shams University", "Egypt", "university"),
    ("Alexandria University", "Egypt", "university"),
    ("The American University in Cairo", "Egypt", "university"),
    ("Mansoura University", "Egypt", "university"),
    ("Assiut University", "Egypt", "university"),
    ("Helwan University", "Egypt", "university"),
    ("University of Tunis", "Tunisia", "university"),
    ("University of Sfax", "Tunisia", "university"),
    ("University of Carthage", "Tunisia", "university"),
    ("University of Algiers", "Algeria", "university"),
    ("University of Oran", "Algeria", "university"),
    ("University of Constantine", "Algeria", "university"),
    ("Mohammed V University", "Morocco", "university"),
    ("Cadi Ayyad University", "Morocco", "university"),
    ("Hassan II University of Casablanca", "Morocco", "university"),
    ("Al Akhawayn University", "Morocco", "university"),
    ("University of Tripoli", "Libya", "university"),
    ("University of Benghazi", "Libya", "university"),
    ("Arizona State University", "United States", "university"),
    ("Massachusetts Institute of Technology", "United States", "university"),
    ("Stanford University", "United States", "university"),
    ("Carnegie Mellon University", "United States", "university"),
    ("University of California Berkeley", "United States", "university"),
    ("Georgia Institute of Technology", "United States", "university"),
    ("University of Illinois Urbana-Champaign", "United States", "university"),
    ("University of Michigan", "United States", "university"),
    ("New York University", "United States", "university"),
    ("Columbia University", "United States", "university"),
    ("Harvard University", "United States", "university"),
    ("Princeton University", "United States", "university"),
    ("Yale University", "United States", "university"),
    ("University of Washington", "United States", "university"),
    ("Purdue University", "United States", "university"),
    ("University of Texas at Austin", "United States", "university"),
    ("University of Maryland", "United States", "university"),
    ("Northeastern University", "United States", "university"),
    ("University of Oxford", "United Kingdom", "university"),
    ("University of Cambridge", "United Kingdom", "university"),
    ("Imperial College London", "United Kingdom", "university"),
    ("University College London", "United Kingdom", "university"),
    ("University of Edinburgh", "United Kingdom", "university"),
    ("University of Manchester", "United Kingdom", "university"),
    ("King’s College London", "United Kingdom", "university"),
    ("University of Bristol", "United Kingdom", "university"),
    ("University of Warwick", "United Kingdom", "university"),
    ("University of Glasgow", "United Kingdom", "university"),
    ("ETH Zurich", "Switzerland", "university"),
    ("EPFL", "Switzerland", "university"),
    ("Technical University of Munich", "Germany", "university"),
    ("RWTH Aachen University", "Germany", "university"),
    ("University of Heidelberg", "Germany", "university"),
    ("Sorbonne University", "France", "university"),
    ("Sciences Po", "France", "university"),
    ("École Polytechnique", "France", "university"),
    ("PSL University", "France", "university"),
    ("University of Amsterdam", "Netherlands", "university"),
    ("Delft University of Technology", "Netherlands", "university"),
    ("KU Leuven", "Belgium", "university"),
    ("University of Copenhagen", "Denmark", "university"),
    ("KTH Royal Institute of Technology", "Sweden", "university"),
    ("University of Helsinki", "Finland", "university"),
    ("University of Oslo", "Norway", "university"),
    ("University of Toronto", "Canada", "university"),
    ("University of British Columbia", "Canada", "university"),
    ("McGill University", "Canada", "university"),
    ("University of Waterloo", "Canada", "university"),
    ("University of Melbourne", "Australia", "university"),
    ("University of Sydney", "Australia", "university"),
    ("Australian National University", "Australia", "university"),
    ("University of New South Wales", "Australia", "university"),
    ("University of Auckland", "New Zealand", "university"),
    ("University of Tokyo", "Japan", "university"),
    ("Kyoto University", "Japan", "university"),
    ("Seoul National University", "South Korea", "university"),
    ("KAIST", "South Korea", "university"),
    ("National University of Singapore", "Singapore", "university"),
    ("Nanyang Technological University", "Singapore", "university"),
    ("Tsinghua University", "China", "university"),
    ("Peking University", "China", "university"),
    ("University of Hong Kong", "Hong Kong", "university"),
    ("Indian Institute of Technology Bombay", "India", "university"),
    ("Indian Institute of Technology Delhi", "India", "university"),
    ("Indian Institute of Science", "India", "university"),
    ("University of Delhi", "India", "university"),
    ("American University of Beirut", "Lebanon", "university"),
    ("King Fahd University of Petroleum and Minerals", "Saudi Arabia", "university"),
    ("King Abdullah University of Science and Technology", "Saudi Arabia", "university"),
    ("Qatar University", "Qatar", "university"),
    ("Khalifa University", "United Arab Emirates", "university"),
    ("American University of Sharjah", "United Arab Emirates", "university"),
    ("Tel Aviv University", "Israel", "university"),
    ("Technion – Israel Institute of Technology", "Israel", "university"),
    ("University of São Paulo", "Brazil", "university"),
    ("University of Buenos Aires", "Argentina", "university"),
    ("National Autonomous University of Mexico", "Mexico", "university"),
    ("University of Chile", "Chile", "university"),
    ("University of the Andes Colombia", "Colombia", "university"),
    ("Community — refugees and host community", "Regional", "community"),
]
